@base_address=https://localhost:7092/api/v1/users

### Get all users
GET {{base_address}}
Accept: application/json


### Get a user by ID
GET {{base_address}}/7
Accept: application/json


### Create a user
POST {{base_address}}
Content-Type: application/json

{
  "firstName": "J",
  "lastName": "D"
}

### Update user
PUT {{base_address}}/9
Content-Type: application/json

{
  "firstName": "Johnny",
  "lastName": "Bravo"
}



### Delete a user
DELETE {{base_address}}/1
Accept: application/json